name: my workflow
##on: push
on: workflow_dispatch

jobs:
    my-cool-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo ##create action
          uses: actions/checkout@v4.1.1
        - name: Print project name and current branch
          run: |
           echo "Project name is ${{ github.repository }} ";
           echo "Current branch is ${{ github.ref }}"
