name: Run Unit Tests

on: 
  workflow_dispatch:
  
jobs:
  run-unit-tests:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ##create action
        uses: actions/checkout@v4.1.1 ##uses the checkout extension from github-marketplace

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
          
      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Unit Tests
        run: dotnet test ToDoList.Tests/ToDoList.Tests.csproj --no-build
